### ISSUE TITLE
Docs for surveys endpoint

### ISSUE THREAD

**Issue by fjaskolski** [livechat/livechat-public-docs#45]
**Where**
https://github.com/livechat/livechat-public-docs/tree/master/rest-api

**Todo**
- [ ] add `_surveys.md` with documentation of surveys endpoint
- [ ] update the local index file ([index.html.md](https://github.com/livechat/livechat-public-docs/blob/master/rest-api/index.html.md))
- [ ] update the excerpt ([_rest-api.md](https://github.com/livechat/livechat-public-docs/blob/master/_rest-api.md)) at the home page

**Comment by tarunvelli** [comment]
Hey, i have gone through the website and kinda figured out the survey endpoints, can i take this up? and any pointers that might be helpful?

my overview
