### ISSUE TITLE
Update the building integration guide

### ISSUE THREAD

**Issue by fjaskolski** [livechat/livechat-public-docs#46]
**Where**
https://github.com/livechat/livechat-public-docs/tree/master/build-integration

**Todo**
- [ ] update the information on authorization (OAuth2.0),
- [ ] describe other types of integrations,
- [ ] review the existing examples and create ready to use ones,
- [ ] check if the [data types](https://docs.livechatinc.com/build-integration/#webhook-data-types) are up-to-date.
- [ ] ?
