### ISSUE TITLE
Guides about popular use cases

### ISSUE THREAD

**Issue by fjaskolski** [livechat/livechat-public-docs#48]
**Where**
https://github.com/livechat/livechat-public-docs/

**Todo**
- [ ] create a separate section **Guides** for guide-like articles,
- [ ] article on using REST-API to create reports,
- [ ] article on using Sign in with LiveChat,
- [ ] article on using Agent App Extension,
- [ ] article on using ...,
- [ ] move "Build your integration" to the Guides section.
